import os

APP_NAME = "IKONU Ingest Station"

MOUNT_BASE = os.environ.get("INGEST_MOUNT_BASE", "/media/pi")
MASTER_VOLUME_NAME = os.environ.get("INGEST_MASTER_NAME", "MASTER")

PROJECT_PREFIX = os.environ.get("INGEST_PROJECT_PREFIX", "IMPORT")

PORT = int(os.environ.get("INGEST_PORT", "8080"))
HOST = "0.0.0.0"

EXCLUDED_NAMES = {
    MASTER_VOLUME_NAME,
    "boot",
    "rootfs"
}

RUSHES_FOLDER = "01_RUSHES"
AUDIO_FOLDER = "02_AUDIO"
PROXIES_FOLDER = "03_PROXIES"
PROJECT_FOLDER = "04_PROJECT"
EXPORTS_FOLDER = "05_EXPORTS"
REPORTS_FOLDER = "99_REPORTS"
